### PR TITLE
Extract event handlers

### PR DESCRIPTION
**Pull request by mitar**

### CODE REVIEW

**Comment by vsivsi** [comment]
Looks like this failed on travisCI.  I haven't looked into it.  Is this necessary?  Can't you just use [`removeListener`]( https://nodejs.org/api/events.html#events_emitter_removelistener_event_listener) to remove/replace the unwanted default behavior?

**Comment by mitar** [comment]
The issue is that `removeListener` expects the handler function to be removed. And because functions are anonymous, inline, you cannot really do that. So currently I am doing:

```coffee
jobCollection._callListener.removeListener 'call', jobCollection._callListener._events.call[0]
```

But I think you see why I would want something more ... cleaner? :-)

BTW, `@events.on` returns `@events`. So:

```coffee
 @_errorListener = @events.on 'error', (msg) =>
  user = userHelper msg.userId, msg.connection
  @_toLog user, msg.method, "#{msg.error}"
```

In fact means that ` @_errorListener` is the same as `@events`. Sadly it is not a handle one could use to remove the event listener. I would love it if it would be like that. But it is not. This is probably why you code it like that. So one option is to then do:

```coffee
 @_errorListener = (msg) =>
  user = userHelper msg.userId, msg.connection
  @_toLog user, msg.method, "#{msg.error}"
@events.on 'error',  @_errorListener
```

But that is then very similar to what I did in this pull request. :-)

**Comment by mitar** [comment]
Updated the pull request. Tests should pass now.

**Comment by vsivsi** [comment]
I just made you a collaborator.  You're thinking about this project far more than I am at the moment.  Go to town and let me know when you think you're ready and I'll review and publish to Atmosphere when I'm ready.  I like to develop on the `dev` branch to keep the master stable.  Let me know if you also need access to `meteor-job`

**Comment by mitar** [comment]
OK, so should code changes go to `dev`, and documentation fixes to `master`?

**Comment by vsivsi** [comment]
Yes, unless the documentation goes with (currently) dev-only changes.

**Comment by mitar** [comment]
OK.

**Comment by mitar** [comment]
Merged into `dev`.

**Pull request closed without merging**
