### PR TITLE
Update README to match current Job API

### PR DESCRIPTION
**Pull request by kahmali**
Update Job constructor in the "Job API" and "Quick Example" sections of
the README to match the current API (first param should be the name of
the JobCollection instead of the collection itself).

### CODE REVIEW

**Comment by kahmali** [comment]
I believe this is related to #69 (and possibly #44), as well as this issue from `meteor-job`: https://github.com/vsivsi/meteor-job/issues/6.

When i followed the Quick example I got the errors mentioned in #44 until I used a string as the first param to the Job constructor as mentioned in #69.

**Comment by vsivsi** [comment]
Hi, thanks for the PR.  Does job-collection pass its unit tests in your environment.  

The unit tests cover this case (passing a jc object instead of a string) and pass on every system I have tried to run them on...

See for instance:
https://github.com/vsivsi/meteor-job-collection/blob/master/job_collection_tests.coffee#L110

People keep some version of this issue, and I keep not being able to reproduce it, so rather than updating the docs, I'd like to work through figuring out what is different about your environment that is causing the problem you are seeing.

Can your please try this:
```sh
mkdir jcTest
git clone --recursive https://github.com/vsivsi/meteor-job-collection.git jcTest
cd jcTest
meteor test-packages ./
mkdir jcTest
git clone --recursive https://github.com/vsivsi/meteor-job-collection.git jcTest
cd jcTest
meteor test-packages ./
```

Now load `http://localhost:3000` in your browser and report back what you see.  Top of the page  should be:

```
All tests pass!  NNNNNN ms  Passed 29 of 29
.
.
.
```

**Comment by kahmali** [comment]
How very amateur of me not to check the version I was using! Sorry about that. For some reason (maybe some constraint imposed by a related dependency), I was using v0.0.18 when I didn't specify a version. I just specified the version as 1.1.2 (currently the latest release), and that appears to have resolved the issue. I should have known to check that before making this PR. 

I can try running these tests when I have some free time, if you think it would still help. I'm in the midst of finals so it probably wouldn't be until late next week unfortunately. Should we go ahead and close this PR?

**Comment by vsivsi** [comment]
No worries, we've all made that mistake. Go ahead and leave this open until you get a chance to test everything out.

**Comment by vsivsi** [comment]
I'm assuming this is resolved on your end.

**Pull request closed without merging**
